DROP SEQUENCE SEQ_MEMBER_NO;
DROP TABLE TBL_MEMBER;

CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE TABLE TBL_MEMBER (
  MEMBER_NO NUMBER PRIMARY KEY,
  MEMBER_ID VARCHAR2(30) UNIQUE,
  MEMBER_PWD VARCHAR2(30) NOT NULL,
  MEMBER_NAME VARCHAR2(30),
  GENDER VARCHAR2(10) CHECK(GENDER IN ('M', 'F')),
  EMAIL VARCHAR2(50),
  PHONE VARCHAR2(30),
  ADDRESS VARCHAR2(100),
  AGE NUMBER CHECK(AGE > 0),
  ENROLL_DATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '김진호', 'M', 'kim_jh@greedy.com', '010-1234-1234', '경기도 남양주시', '20', sysdate);
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02', '김용승', 'M', 'kim_ys@greedy.com', '010-1234-5678', '서울시 서초구', '19', sysdate);
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03', '유승제', 'M', 'yoo_sj@greedy.com', '010-1234-3556', '서울시 관악구', '12', sysdate);
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user04', 'pass04', '허은주', 'F', 'heo_ej@greedy.com', '010-1234-0008', '서울시 영등포구', '27', sysdate);
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'user05', 'pass05', '우별림', 'F', 'woo_bl@greedy.com', '010-1234-7854', '서울시 서대문구', '20', sysdate);

COMMIT;

SELECT * FROM TBL_MEMBER;